name: Publish Windows and macOS Release

on:
  push:
    brances: [main]

jobs:
  build-release:
    runs-on: windows-macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "version=$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.dmg
